# Use the official Node.js image as a base
FROM node:18

# Set the working directory
WORKDIR /usr/src/app

# Install dependencies
COPY server/package*.json ./
RUN npm install

# Copy the rest of the server code
COPY server/ .

# Expose port 3000 for the server
EXPOSE 3100

# Start the server using the docker command
CMD ["npm", "run", "dev:docker"]
